package cliente;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelos.Alumno;

public class GUI_Alumno extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    int op=0;
    public GUI_Alumno() {
        initComponents();
        getStudents();
    }

    public void getStudents() {
        AlumnoRequest cliente;
        Alumno alumno = new Alumno();
        cliente = new AlumnoRequest(this, alumno, 'l');
        Thread peticion = new Thread(cliente);
        peticion.start();
    }

    public void listStudents(ArrayList<Alumno> alumnos) {
        Object[][] students = new Object[alumnos.size()][11];
        String[] columns = {"idAlumno", "Nombre", "Apellido Paterno", "Apellido Materno", "Email", "Calle", "Numero", "Colonia", "Delegacion", "Entidad", "Telefono"};

        for (int i = 0, j = 0; i < alumnos.size(); i++) {
            students[i][j] = "" + alumnos.get(i).getIdAlumno();
            students[i][j + 1] = "" + alumnos.get(i).getNombre();
            students[i][j + 2] = "" + alumnos.get(i).getApellidoPaterno();
            students[i][j + 3] = "" + alumnos.get(i).getApellidoMaterno();
            students[i][j + 4] = "" + alumnos.get(i).getMail();
            students[i][j + 5] = "" + alumnos.get(i).getCalle();
            students[i][j + 6] = "" + alumnos.get(i).getNumero();
            students[i][j + 7] = "" + alumnos.get(i).getColonia();
            students[i][j + 8] = "" + alumnos.get(i).getDelegación();
            students[i][j + 9] = "" + alumnos.get(i).getEntidad();
            students[i][j + 10] = "" + alumnos.get(i).getTelefono();

        }
        tblShowTable.setModel(new DefaultTableModel(students, columns));
    }

    public void setValuesSearched(Alumno alumno) {
        txtNombreAlumno.setText("" + alumno.getNombre());
        txtApellidoP.setText(alumno.getApellidoPaterno());
        txtApellidoM.setText(alumno.getApellidoMaterno());
        txtEmail.setText(alumno.getMail());
        txtCalle.setText(alumno.getCalle());
        txtNumero.setText(alumno.getNumero());
        txtColonia.setText(alumno.getColonia());
        txtDelegacion.setText(alumno.getDelegación());
        txtEntidad.setText(alumno.getEntidad());
        txtTelefono.setText(alumno.getTelefono());

    }

    public Alumno buscarAlumno() {
        AlumnoRequest cliente;
        Alumno alumno = new Alumno();
       // int idAlumno = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el nombre del Alumno ", "Buscar alumno", JOptionPane.QUESTION_MESSAGE));
        int i = tblShowTable.getSelectedRow();
        int idAlumno = Integer.parseInt(tblShowTable.getValueAt(i, 0)+"");
        alumno.setIdAlumno(idAlumno);
        cliente = new AlumnoRequest(this, alumno, 'b');
        Thread peticion = new Thread(cliente);
        peticion.start();
        return alumno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnNuevoAlumno = new javax.swing.JButton();
        btnBuscarAlumno = new javax.swing.JButton();
        btnEliminarAlumno = new javax.swing.JButton();
        btnActualizaAlumno = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        txtDelegacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEntidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de alumnos");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnNuevoAlumno.setText("Agregar");
        btnNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAlumnoActionPerformed(evt);
            }
        });

        btnBuscarAlumno.setText("Buscar");
        btnBuscarAlumno.setEnabled(false);
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });

        btnEliminarAlumno.setText("Eliminar");
        btnEliminarAlumno.setEnabled(false);
        btnEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlumnoActionPerformed(evt);
            }
        });

        btnActualizaAlumno.setText("Actualiza");
        btnActualizaAlumno.setEnabled(false);
        btnActualizaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaAlumnoActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setText("Limpiar");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarAlumno)
                            .addComponent(btnNuevoAlumno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarAlumno)
                            .addComponent(btnActualizaAlumno, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnLimpiarCampos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoAlumno)
                    .addComponent(btnBuscarAlumno))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarAlumno)
                    .addComponent(btnActualizaAlumno))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarCampos))
        );

        jLabel5.setText("Calle");

        jLabel6.setText("Numero");

        jLabel1.setText("Nombre");

        jLabel7.setText("Colonia");

        jLabel2.setText("Apellido Paterno");

        jLabel8.setText("Delegacion");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Email");

        jLabel9.setText("Entidad");

        jLabel10.setText("Telefono");

        tblShowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdAlumno", "Nombre", "Apellido Paterno", "Apellido Materno", "Email", "Calle", "Numero", "Colonia", "Delegacion", "Entidad", "Telefono"
            }
        ));
        tblShowTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblShowTableFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tblShowTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDelegacion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(24, 24, 24)
                        .addComponent(txtEntidad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(txtDelegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(txtEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAlumnoActionPerformed
        AlumnoRequest cliente;
        Alumno alumno = new Alumno();
        alumno.setNombre(txtNombreAlumno.getText());
        alumno.setApellidoPaterno(txtApellidoP.getText());
        alumno.setApellidoMaterno(txtApellidoM.getText());
        alumno.setMail(txtEmail.getText());
        alumno.setCalle(txtCalle.getText());
        alumno.setNumero(txtNumero.getText());
        alumno.setColonia(txtColonia.getText());
        alumno.setDelegación(txtDelegacion.getText());
        alumno.setEntidad(txtEntidad.getText());
        alumno.setTelefono(txtTelefono.getText());
        int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea insertar al alumno?", "Insertar nuevo alumno", JOptionPane.YES_NO_OPTION);
        if (option == 0) {
            cliente = new AlumnoRequest(this, alumno, 1, 'u');
            Thread peticion=new Thread(cliente);
            peticion.start();
        }
        getStudents();
    }//GEN-LAST:event_btnNuevoAlumnoActionPerformed

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        Alumno alumno = new Alumno();
        alumno = buscarAlumno();

    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoActionPerformed
        AlumnoRequest cliente;
        Alumno alumno = new Alumno();
        alumno = buscarAlumno();
        int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar al alumno?", "Eliminar alumno", JOptionPane.YES_NO_OPTION);
        if (option == 0) {
            cliente = new AlumnoRequest(this, alumno, 'd');
            Thread peticion = new Thread(cliente);
            peticion.start();
        }
        limpiar();
    }//GEN-LAST:event_btnEliminarAlumnoActionPerformed
    public void limpiar(){
        txtNombreAlumno.setText("");
        txtApellidoP.setText("");
        txtApellidoM.setText("");
        txtEmail.setText("");
        txtCalle.setText("");
        txtNumero.setText("");
        txtColonia.setText("");
        txtDelegacion.setText("");
        txtEntidad.setText("");
        txtTelefono.setText("");   
    }
    private void btnActualizaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaAlumnoActionPerformed
        btnNuevoAlumno.setEnabled(false);
        btnEliminarAlumno.setEnabled(false);
        btnBuscarAlumno.setEnabled(false);
        Alumno alumno = new Alumno();
        AlumnoRequest cliente;
         if(op!=2){
            alumno = buscarAlumno();
            alumno.setNombre(txtNombreAlumno.getText());
            alumno.setApellidoPaterno(txtApellidoP.getText());
            alumno.setApellidoMaterno(txtApellidoM.getText());
            alumno.setMail(txtEmail.getText());
            alumno.setCalle(txtCalle.getText());
            alumno.setNumero(txtNumero.getText());
            alumno.setColonia(txtColonia.getText());
            alumno.setDelegación(txtDelegacion.getText());
            alumno.setEntidad(txtEntidad.getText());
            alumno.setTelefono(txtTelefono.getText());
            //setValuesSearched(alumno);
            op++;
             System.out.println("entro1");
         }
        if(op==2){
            int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea actualizar al alumno?", "Actualizar alumno", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                   System.out.println("entro2");
                cliente = new AlumnoRequest(this, alumno, 2, 'u');//Primer parametro=datos,Segundo parametro: 1=insert 2=update,Tercer parametro:'u'=update&insert 'd'=delete 'b'=buscar 'l'=listar
                Thread peticion = new Thread(cliente);
                peticion.start();//Peticion asincrona
                op=0;
                limpiar();
                btnNuevoAlumno.setEnabled(true);
                btnActualizaAlumno.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnActualizaAlumnoActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiar();
        getStudents();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void tblShowTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblShowTableFocusGained
        btnActualizaAlumno.setEnabled(true);
        btnBuscarAlumno.setEnabled(true);
        btnEliminarAlumno.setEnabled(true);
    }//GEN-LAST:event_tblShowTableFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Alumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizaAlumno;
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton btnEliminarAlumno;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnNuevoAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblShowTable;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtDelegacion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEntidad;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
