/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Curso;

/**
 *
 * @author Steeltwins
 */
public class GUI_Curso extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Curso
     */
    public GUI_Curso() {
        initComponents();
        getCourses();
    }
    
     public void getCourses() {
        CursoRequest cliente;
        Curso curso = new Curso();
        cliente = new CursoRequest(this, curso, 'l');
        Thread peticion = new Thread(cliente);
        peticion.start();
    }

    public void listCourses(ArrayList<Curso> cursos) {
        Object[][] courses = new Object[cursos.size()][5];
        String[] columns = {"idCurso","Nombre", "Fecha de Inicio", "Fecha Fin", "Cuota de Recuperacion"};

        for (int i = 0, j = 0; i < cursos.size(); i++) {
            courses[i][j] = "" + cursos.get(i).getIdCurso();
            courses[i][j+1] = "" + cursos.get(i).getNombre();
            courses[i][j + 2] = "" + cursos.get(i).getFechaInicio();
            courses[i][j + 3] = "" + cursos.get(i).getFechaTermino();
            courses[i][j + 4] = "" + cursos.get(i).getCuota();

        }
        tblShowTable.setModel(new DefaultTableModel(courses, columns));
    }

    public void setValuesSearched(Curso curso) {
        txtNombre.setText("" + curso.getNombre());
        txtFechaInicio.setText(curso.getFechaInicio());
        txtFechaFin.setText(curso.getFechaTermino());
        txtCuotaRecuperacion.setText(""+curso.getCuota());
    }

    public Curso buscarCurso() {
        CursoRequest cliente;
        Curso curso = new Curso();
        //int idCurso = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el id del Curso ", "Buscar curso", JOptionPane.QUESTION_MESSAGE));
        int i = tblShowTable.getSelectedRow();
        int idCurso = Integer.parseInt(tblShowTable.getValueAt(i, 0)+"");
        
        curso.setIdCurso(idCurso);
        cliente = new CursoRequest(this, curso, 'b');
        Thread peticion = new Thread(cliente);
        peticion.start();
        return curso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCuotaRecuperacion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnNuevoCurso = new javax.swing.JButton();
        btnBuscarCurso = new javax.swing.JButton();
        btnEliminarCurso = new javax.swing.JButton();
        btnActualizaCurso = new javax.swing.JButton();
        btnListarCursos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de cursos");

        jLabel1.setText("Nombre");

        jLabel2.setText("Fecha inicio");

        jLabel3.setText("Fecha fin");

        jLabel4.setText("Cuota de recuperacion");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnNuevoCurso.setText("Nuevo");
        btnNuevoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCursoActionPerformed(evt);
            }
        });

        btnBuscarCurso.setText("Buscar");
        btnBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCursoActionPerformed(evt);
            }
        });

        btnEliminarCurso.setText("Eliminar");
        btnEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCursoActionPerformed(evt);
            }
        });

        btnActualizaCurso.setText("Actualiza");
        btnActualizaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaCursoActionPerformed(evt);
            }
        });

        btnListarCursos.setText("Limpiar");
        btnListarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNuevoCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarCurso))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnEliminarCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizaCurso)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarCursos)
                .addGap(54, 54, 54))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCurso)
                    .addComponent(btnBuscarCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarCurso)
                    .addComponent(btnActualizaCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListarCursos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblShowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idCurso", "Nombre", "Fecha Inicio", "Fecha Fin", "Cuota de recuperacion"
            }
        ));
        jScrollPane1.setViewportView(tblShowTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtCuotaRecuperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCuotaRecuperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCursoActionPerformed
        CursoRequest cliente;
        Curso curso = new Curso();
        curso.setNombre(txtNombre.getText());
        curso.setFechaInicio(txtFechaInicio.getText());
        curso.setFechaTermino(txtFechaFin.getText());
        curso.setCuota(Double.parseDouble(txtCuotaRecuperacion.getText()));
        int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea insertar el curso?", "Insertar nuevo curso", JOptionPane.YES_NO_OPTION);
        if (option == 0) {
            cliente = new CursoRequest(this, curso, 1, 'u');
            Thread peticion=new Thread(cliente);
            peticion.start();
        }
        getCourses();
    }//GEN-LAST:event_btnNuevoCursoActionPerformed

    private void btnBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCursoActionPerformed
        Curso alumno = new Curso();
        alumno = buscarCurso();
    }//GEN-LAST:event_btnBuscarCursoActionPerformed

    private void btnEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCursoActionPerformed
        CursoRequest cliente;
        Curso curso = new Curso();
        curso = buscarCurso();
        int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar al curso?", "Eliminar curso", JOptionPane.YES_NO_OPTION);
        if (option == 0) {
            cliente = new CursoRequest(this, curso, 'd');
            Thread peticion = new Thread(cliente);
            peticion.start();
        }
    }//GEN-LAST:event_btnEliminarCursoActionPerformed

    private void btnActualizaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaCursoActionPerformed
        Curso curso = new Curso();
        CursoRequest cliente;
        curso = buscarCurso();
        curso.setNombre(txtNombre.getText());
        curso.setFechaInicio(txtFechaInicio.getText());
        curso.setFechaTermino(txtFechaFin.getText());
        curso.setCuota(Double.parseDouble(txtCuotaRecuperacion.getText()));
        
        int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea actualizar el curso?", "Actualizar curso", JOptionPane.YES_NO_OPTION);
        if (option == 0) {

            cliente = new CursoRequest(this, curso, 2, 'u');//Primer parametro=datos,Segundo parametro: 1=insert 2=update,Tercer parametro:'u'=update&insert 'd'=delete 'b'=buscar 'l'=listar
            Thread peticion = new Thread(cliente);
            peticion.start();//Peticion asincrona

        }
    }//GEN-LAST:event_btnActualizaCursoActionPerformed

    private void btnListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCursosActionPerformed
        getCourses();
    }//GEN-LAST:event_btnListarCursosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Curso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizaCurso;
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnEliminarCurso;
    private javax.swing.JButton btnListarCursos;
    private javax.swing.JButton btnNuevoCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblShowTable;
    private javax.swing.JTextField txtCuotaRecuperacion;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
