
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Alumno;
import modelos.Asignacion;
import modelos.Curso;

/**
 *
 * @author Steeltwins
 */
public class GUI_Asignacion extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Asignacion
     */
    public GUI_Asignacion() {
        initComponents();
        cboAlumno.removeAllItems();
        cboCurso.removeAllItems();
        getAssignations();
        // getStudents();
        //getCourses();
    }

    public void getCourses() {
        AsignacionRequest cliente;
        cliente = new AsignacionRequest(this, 'c');
        Thread peticion = new Thread(cliente);
        peticion.start();
    }

    public void listCourses(ArrayList<Curso> cursos) {
        for (int i = 0, j = 0; i < cursos.size(); i++) {
            cboCurso.addItem(cursos.get(i).getNombre() + "-" + cursos.get(i).getIdCurso());
        }
    }

    public void getStudents() {
        AsignacionRequest cliente;
        cliente = new AsignacionRequest(this, 's');
        Thread peticion = new Thread(cliente);
        peticion.start();
    }

    public void listStudents(ArrayList<Alumno> alumnos) {
        for (int i = 0, j = 0; i < alumnos.size(); i++) {
            cboAlumno.addItem(alumnos.get(i).getNombre() + "-" + alumnos.get(i).getIdAlumno());
        }
    }

    public void getAssignations() {
        AsignacionRequest cliente;
        cliente = new AsignacionRequest(this, 'l');
        Thread peticion = new Thread(cliente);
        peticion.start();
    }

    public void listAssignations(ArrayList<Asignacion> asignacion) {
        Object[][] assigned = new Object[asignacion.size()][4];
        String[] columns = {"idCurso", "idAlumno", "Horario", "Tipo de Curso"};

        for (int i = 0, j = 0; i < asignacion.size(); i++) {
            assigned[i][j] = "" + asignacion.get(i).getIdCurso();
            assigned[i][j + 1] = "" + asignacion.get(i).getIdAlumno();
            assigned[i][j + 2] = "" + asignacion.get(i).getHorario();
            assigned[i][j + 3] = "" + asignacion.get(i).getTipo();

        }
        tblShowTable.setModel(new DefaultTableModel(assigned, columns));
    }

    public void setValuesSearched(Asignacion asignacion) {
//        cboAlumno.setSelectedItem(asignacion.getIdAlumno());
//        cboCurso.setSelectedItem(asignacion.getIdCurso());
//        txtHorario.setText(asignacion.getHorario());
//        spTipoDeCurso.setValue(asignacion.getTipo());
        Object[][] assigned = new Object[1][4];
        String[] columns = {"idCurso", "idAlumno", "Horario", "Tipo de Curso"};
        assigned[0][0] = "" + asignacion.getIdCurso();
        assigned[0][1] = "" + asignacion.getIdAlumno();
        assigned[0][2] = "" + asignacion.getHorario();
        assigned[0][3] = "" + asignacion.getTipo();
        tblShowTable.setModel(new DefaultTableModel(assigned, columns));
    }

    public Asignacion buscarAsignacion() {
        AsignacionRequest cliente;
        Asignacion asignacion = new Asignacion();
        //int idCurso = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el id del Curso ", "Buscar asignacion", JOptionPane.QUESTION_MESSAGE));
        int i = tblShowTable.getSelectedRow();
        int idCurso = Integer.parseInt(tblShowTable.getValueAt(i, 0)+"");
        int idAlumno = Integer.parseInt(tblShowTable.getValueAt(i, 1)+"");
        asignacion.setIdCurso(idCurso);
        //int idAlumno = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el id del Alumno ", "Buscar asignacion", JOptionPane.QUESTION_MESSAGE));
        asignacion.setIdAlumno(idAlumno);
        cliente = new AsignacionRequest(this, asignacion, 'b');
        Thread peticion = new Thread(cliente);
        peticion.start();
        return asignacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboAlumno = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHorario = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnNuevoAsignacion = new javax.swing.JButton();
        btnBuscarAsignacion = new javax.swing.JButton();
        btnEliminarAsignacion = new javax.swing.JButton();
        btnActualizaAsignacion = new javax.swing.JButton();
        btnListarAsignaciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowTable = new javax.swing.JTable();
        spTipoDeCurso = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Asignaciones");

        jLabel1.setText("Alumno");

        cboAlumno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboAlumnoMouseClicked(evt);
            }
        });

        jLabel2.setText("Curso");

        cboCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboCursoMouseClicked(evt);
            }
        });

        jLabel3.setText("Horario");

        jLabel4.setText("Tipo de curso");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnNuevoAsignacion.setText("Nuevo");
        btnNuevoAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAsignacionActionPerformed(evt);
            }
        });

        btnBuscarAsignacion.setText("Buscar");
        btnBuscarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignacionActionPerformed(evt);
            }
        });

        btnEliminarAsignacion.setText("Eliminar");
        btnEliminarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAsignacionActionPerformed(evt);
            }
        });

        btnActualizaAsignacion.setText("Actualiza");
        btnActualizaAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaAsignacionActionPerformed(evt);
            }
        });

        btnListarAsignaciones.setText("Listar");
        btnListarAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAsignacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnEliminarAsignacion)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizaAsignacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNuevoAsignacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarAsignacion)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarAsignaciones)
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoAsignacion)
                    .addComponent(btnBuscarAsignacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarAsignacion)
                    .addComponent(btnActualizaAsignacion))
                .addGap(18, 18, 18)
                .addComponent(btnListarAsignaciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblShowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idCurso", "idAlumno", "Horario", "Tipo de curso"
            }
        ));
        jScrollPane1.setViewportView(tblShowTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(spTipoDeCurso))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)
                                .addComponent(cboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboCurso, 0, 116, Short.MAX_VALUE)
                                    .addComponent(txtHorario))))
                        .addGap(37, 37, 37)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spTipoDeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAsignacionActionPerformed
        AsignacionRequest cliente;
        Asignacion asignacion = new Asignacion();
        System.out.println("idAlumno: " + cboAlumno.getSelectedItem().toString().substring(cboAlumno.getSelectedItem().toString().indexOf("-")));
        System.out.println("idAlumno: " + cboCurso.getSelectedItem().toString().substring(cboCurso.getSelectedItem().toString().indexOf("-") + 1));
        asignacion.setIdAlumno(Integer.parseInt(cboAlumno.getSelectedItem().toString().substring(cboAlumno.getSelectedItem().toString().indexOf("-") + 1)));
        asignacion.setIdCurso(Integer.parseInt(cboCurso.getSelectedItem().toString().substring(cboCurso.getSelectedItem().toString().indexOf("-") + 1)));
        asignacion.setHorario(txtHorario.getText());
        asignacion.setTipo((int) spTipoDeCurso.getValue());
        int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea crear la asignacion?", "Crear asignacion", JOptionPane.YES_NO_OPTION);
        if (option == 0) {
            cliente = new AsignacionRequest(this, asignacion, 1, 'u');
            Thread peticion = new Thread(cliente);
            peticion.start();
        }
    }//GEN-LAST:event_btnNuevoAsignacionActionPerformed

    private void btnBuscarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsignacionActionPerformed
        Asignacion asignacion = new Asignacion();
        asignacion = buscarAsignacion();
    }//GEN-LAST:event_btnBuscarAsignacionActionPerformed

    private void btnEliminarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAsignacionActionPerformed
        AsignacionRequest cliente;
        Asignacion asignacion = new Asignacion();
        asignacion = buscarAsignacion();
        int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar la asignacion?", "Eliminar asignacion", JOptionPane.YES_NO_OPTION);
        if (option == 0) {
            cliente = new AsignacionRequest(this, asignacion, 'd');
            Thread peticion = new Thread(cliente);
            peticion.start();
        }
    }//GEN-LAST:event_btnEliminarAsignacionActionPerformed

    private void btnActualizaAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaAsignacionActionPerformed
        Asignacion asignacion = new Asignacion();
        AsignacionRequest cliente;
        asignacion = buscarAsignacion();
        asignacion.setHorario(txtHorario.getText());
        asignacion.setTipo((int) spTipoDeCurso.getValue());

        int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea actualizar la asignacion?", "Actualizar asignacion", JOptionPane.YES_NO_OPTION);
        if (option == 0) {

            cliente = new AsignacionRequest(this, asignacion, 2, 'u');//Primer parametro=datos,Segundo parametro: 1=insert 2=update,Tercer parametro:'u'=update&insert 'd'=delete 'b'=buscar 'l'=listar
            Thread peticion = new Thread(cliente);
            peticion.start();//Peticion asincrona

        }
    }//GEN-LAST:event_btnActualizaAsignacionActionPerformed

    private void btnListarAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAsignacionesActionPerformed
        getAssignations();
    }//GEN-LAST:event_btnListarAsignacionesActionPerformed

    private void cboCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCursoMouseClicked
        cboCurso.removeAllItems();
        getCourses();
    }//GEN-LAST:event_cboCursoMouseClicked

    private void cboAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboAlumnoMouseClicked
        cboAlumno.removeAllItems();
        getStudents();
    }//GEN-LAST:event_cboAlumnoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Asignacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizaAsignacion;
    private javax.swing.JButton btnBuscarAsignacion;
    private javax.swing.JButton btnEliminarAsignacion;
    private javax.swing.JButton btnListarAsignaciones;
    private javax.swing.JButton btnNuevoAsignacion;
    private javax.swing.JComboBox<String> cboAlumno;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spTipoDeCurso;
    private javax.swing.JTable tblShowTable;
    private javax.swing.JTextField txtHorario;
    // End of variables declaration//GEN-END:variables
}
